version: 2

mkdocs:
  configuration: mkdocs-docs/mkdocs.yml
  fail_on_warning: false

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.8" 