site_name: Manticore OrderBook
site_url: https://manticoretechnologies.github.io/manticore-orderbook/
site_description: High-performance OrderBook implementation for cryptocurrency exchanges
site_author: Manticore Technologies

repo_name: manticoretechnologies/manticore-orderbook
repo_url: https://github.com/manticoretechnologies/manticore-orderbook

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - API Reference: api-reference.md
  - Integration: integration.md
  - Events System: events.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manticoretechnologies
    - icon: fontawesome/solid/globe
      link: https://manticore.technology
